const assert = require('node:assert/strict');
const fs = require('node:fs');
const { JSDOM } = require('jsdom');
const source = fs.readFileSync('web.py', 'utf8');
const start = source.indexOf('function echapperHtml(texte)');
const end = source.indexOf('function ajouterMessage(texte, classe)');
assert.ok(start >= 0 && end > start);
const dom = new JSDOM('<!doctype html><body><div id="chat"></div></body>', { url: 'https://dashle.test/', runScripts: 'outside-only' });
dom.window.eval(fs.readFileSync('static/vendor/marked.min.js', 'utf8'));
dom.window.eval(fs.readFileSync('static/vendor/purify.min.js', 'utf8'));
assert.ok(dom.window.marked);
assert.ok(dom.window.DOMPurify);
dom.window.eval(source.slice(start, end));
const render = dom.window.rendreMarkdown;
const nl = '\n';
const tick = String.fromCharCode(96);
assert.ok(render('**Google Play Store**').includes('<strong>Google Play Store</strong>'));
assert.match(render(['1. **Sur smartphone**', '   - Ouvre l’application', '   - Connecte-toi'].join(nl)), /<ol>.*<ul>/s);
assert.match(render(['| A | B |', '|---|---|', '| 1 | 2 |'].join(nl)), /<table>/);
assert.match(render(tick.repeat(3) + 'js' + nl + 'const x = 1;' + nl + tick.repeat(3)), /Copier le code/);
const xss = render('<script>alert(1)</script><img src=x onerror="alert(2)"><a href="javascript:alert(3)">x</a>');
assert.doesNotMatch(xss, /<script|onerror|javascript:/i);
assert.match(xss, /<a[^>]+target="_blank"[^>]+rel="noopener noreferrer"/);
const partial = render('Voici **une réponse en cours');
assert.match(partial, /Voici/);
assert.doesNotMatch(partial, /<[^>]*$/);
assert.doesNotMatch(partial, /<script/i);
assert.equal(dom.window.texteSansMarqueursMarkdown('**gras** _italique_ ' + tick + 'code' + tick + ' [lien](https://example.com)'), 'gras italique code lien');
console.log('Markdown jsdom: OK');